[package]
name = "const_units_uuse"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.28"
quote = "1.0.32"
proc-macro2 = "1.0.59"
